version: '3.8'

services:
  # PayTR Test Suite - Smoke Tests
  paytr-smoke-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: paytr-smoke-tests
    environment:
      - TEST_SUITE=smoke-enhanced
      - BROWSER=chrome
      - ENVIRONMENT=test
      - HEADLESS=true
      - PARALLEL=false
      - THREAD_COUNT=1
      - GENERATE_REPORTS=true
      - MAVEN_OPTS=-Xmx2048m
    volumes:
      - ./target/enhanced-reports:/app/target/enhanced-reports
      - ./target/logs:/app/target/logs
      - ./target/screenshots:/app/target/screenshots
      - ./target/allure-results:/app/target/allure-results
    command: ["./scripts/run-enhanced-tests.sh", "--suite", "smoke-enhanced", "--browser", "chrome", "--headless", "--reports"]
    networks:
      - paytr-test-network
    profiles:
      - smoke

  # PayTR Test Suite - Comprehensive Tests
  paytr-comprehensive-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: paytr-comprehensive-tests
    environment:
      - TEST_SUITE=comprehensive-enhanced
      - BROWSER=chrome
      - ENVIRONMENT=test
      - HEADLESS=true
      - PARALLEL=false
      - THREAD_COUNT=1
      - GENERATE_REPORTS=true
      - MAVEN_OPTS=-Xmx4096m
    volumes:
      - ./target/enhanced-reports:/app/target/enhanced-reports
      - ./target/logs:/app/target/logs
      - ./target/screenshots:/app/target/screenshots
      - ./target/allure-results:/app/target/allure-results
    command: ["./scripts/run-enhanced-tests.sh", "--suite", "comprehensive-enhanced", "--browser", "chrome", "--headless", "--reports"]
    networks:
      - paytr-test-network
    profiles:
      - comprehensive

  # PayTR Test Suite - Parallel Execution
  paytr-parallel-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: paytr-parallel-tests
    environment:
      - TEST_SUITE=parallel-enhanced
      - BROWSER=chrome
      - ENVIRONMENT=test
      - HEADLESS=true
      - PARALLEL=true
      - THREAD_COUNT=4
      - GENERATE_REPORTS=true
      - MAVEN_OPTS=-Xmx4096m
    volumes:
      - ./target/enhanced-reports:/app/target/enhanced-reports
      - ./target/logs:/app/target/logs
      - ./target/screenshots:/app/target/screenshots
      - ./target/allure-results:/app/target/allure-results
    command: ["./scripts/run-enhanced-tests.sh", "--suite", "parallel-enhanced", "--browser", "chrome", "--headless", "--parallel", "--threads", "4", "--reports"]
    networks:
      - paytr-test-network
    profiles:
      - parallel

  # PayTR Test Suite - Cross-Browser Testing
  paytr-chrome-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: paytr-chrome-tests
    environment:
      - TEST_SUITE=regression-enhanced
      - BROWSER=chrome
      - ENVIRONMENT=test
      - HEADLESS=true
      - MAVEN_OPTS=-Xmx2048m
    volumes:
      - ./target/enhanced-reports:/app/target/enhanced-reports
      - ./target/logs:/app/target/logs
      - ./target/screenshots:/app/target/screenshots
      - ./target/allure-results:/app/target/allure-results
    command: ["./scripts/run-enhanced-tests.sh", "--suite", "regression-enhanced", "--browser", "chrome", "--headless", "--reports"]
    networks:
      - paytr-test-network
    profiles:
      - cross-browser

  paytr-firefox-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: paytr-firefox-tests
    environment:
      - TEST_SUITE=regression-enhanced
      - BROWSER=firefox
      - ENVIRONMENT=test
      - HEADLESS=true
      - MAVEN_OPTS=-Xmx2048m
    volumes:
      - ./target/enhanced-reports:/app/target/enhanced-reports
      - ./target/logs:/app/target/logs
      - ./target/screenshots:/app/target/screenshots
      - ./target/allure-results:/app/target/allure-results
    command: ["./scripts/run-enhanced-tests.sh", "--suite", "regression-enhanced", "--browser", "firefox", "--headless", "--reports"]
    networks:
      - paytr-test-network
    profiles:
      - cross-browser

  # Selenium Grid Hub (for distributed testing)
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    networks:
      - paytr-test-network
    profiles:
      - grid

  # Selenium Chrome Node
  selenium-chrome:
    image: selenium/node-chrome:4.15.0
    container_name: selenium-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - paytr-test-network
    profiles:
      - grid

  # Selenium Firefox Node
  selenium-firefox:
    image: selenium/node-firefox:4.15.0
    container_name: selenium-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - paytr-test-network
    profiles:
      - grid

  # Test Report Server (Nginx for serving reports)
  test-report-server:
    image: nginx:alpine
    container_name: test-report-server
    ports:
      - "8080:80"
    volumes:
      - ./target/enhanced-reports:/usr/share/nginx/html/reports
      - ./target/allure-report:/usr/share/nginx/html/allure
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - paytr-test-network
    profiles:
      - reports

  # Test Database (PostgreSQL for test data)
  test-database:
    image: postgres:15-alpine
    container_name: test-database
    environment:
      - POSTGRES_DB=paytr_test
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - paytr-test-network
    profiles:
      - database

  # Test Monitoring (Prometheus for metrics)
  prometheus:
    image: prom/prometheus:latest
    container_name: test-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - paytr-test-network
    profiles:
      - monitoring

  # Test Visualization (Grafana for dashboards)
  grafana:
    image: grafana/grafana:latest
    container_name: test-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - paytr-test-network
    profiles:
      - monitoring

networks:
  paytr-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local
  grafana_data:
    driver: local

# Docker Compose Profiles Usage:
# docker-compose --profile smoke up          # Run smoke tests only
# docker-compose --profile comprehensive up  # Run comprehensive tests
# docker-compose --profile parallel up       # Run parallel tests
# docker-compose --profile cross-browser up  # Run cross-browser tests
# docker-compose --profile grid up           # Start Selenium Grid
# docker-compose --profile reports up        # Start report server
# docker-compose --profile database up       # Start test database
# docker-compose --profile monitoring up     # Start monitoring stack
# docker-compose --profile smoke --profile reports up  # Multiple profiles